name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"

    steps:
    - uses: actions/checkout@v1
    - name: Install required dependencies
      run: |
        apt update
        apt install --yes sudo
        sudo apt install --yes --no-install-recommends git
        # workaround for https://github.com/actions/runner/issues/2033
        git config --global --add safe.directory '*'
    - name: Setup .NET
      run: |
        # We need to install `ca-certificates`, otherwise we get these errors in the CI:
        # Unable to load the service index for source https://api.nuget.org/v3/index.json.
        # The SSL connection could not be established, see inner exception.
        # The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
        apt install --yes --no-install-recommends ca-certificates
        apt install --yes --no-install-recommends dotnet6
    - name: Build
      run: dotnet build
